In [ ]:
!pip install konlpy

In [1]:
import pandas as pd
import numpy as np
from konlpy.tag import Okt
from sklearn.feature_extraction.text import CountVectorizer

# 데이터 불러오기

In [2]:
df1 = pd.read_csv('/Users/seungminkoo/Desktop/대학원/프로젝트/HY야쿠르트/2.dcx/2. 클러스터링/1. 독투벡_kmeans_tfidf/[hy]clu0.csv', encoding = 'utf-8-sig', index_col = 0)
df2 = pd.read_csv('/Users/seungminkoo/Desktop/대학원/프로젝트/HY야쿠르트/2.dcx/2. 클러스터링/1. 독투벡_kmeans_tfidf/[hy]clu1.csv', encoding = 'utf-8-sig', index_col = 0)
df3 = pd.read_csv('/Users/seungminkoo/Desktop/대학원/프로젝트/HY야쿠르트/2.dcx/2. 클러스터링/1. 독투벡_kmeans_tfidf/[hy]clu2.csv', encoding = 'utf-8-sig', index_col = 0)
df4 = pd.read_csv('/Users/seungminkoo/Desktop/대학원/프로젝트/HY야쿠르트/2.dcx/2. 클러스터링/1. 독투벡_kmeans_tfidf/[hy]clu3.csv', encoding = 'utf-8-sig', index_col = 0)
df5 = pd.read_csv('/Users/seungminkoo/Desktop/대학원/프로젝트/HY야쿠르트/2.dcx/2. 클러스터링/1. 독투벡_kmeans_tfidf/[hy]clu4.csv', encoding = 'utf-8-sig', index_col = 0)
df6 = pd.read_csv('/Users/seungminkoo/Desktop/대학원/프로젝트/HY야쿠르트/2.dcx/2. 클러스터링/1. 독투벡_kmeans_tfidf/[hy]clu5.csv', encoding = 'utf-8-sig', index_col = 0)

In [3]:
okt = Okt() 

def preprocess_okt(text):
    #text = spacing(text) #띄어쓰기 보정 위에서 했으면 필요없습니다
    pos_words = okt.pos(text, stem=True)
    words = [word for word, tag in pos_words if tag in ['Noun', 'Adjective', 'Verb'] ]
    stopwords = ['의','가','이','은','들','는','좀','잘','걍','과','아니다','이렇다','저렇다','도','다','돼다','최고','되다','를','같다','되었다','오다','가다','으로','자','에','와','한','하다','것','수','있다','않다','그','이다','이었다', '안','억','이건','정도','개']
    stopped_words = [w for w in words if not w in stopwords]
    return ', '.join(stopped_words)

In [7]:
from tqdm import tqdm 
tqdm.pandas()
df1['review_token'] = df1['review'].progress_apply(preprocess_okt)
df2['review_token'] = df2['review'].progress_apply(preprocess_okt)
df3['review_token'] = df3['review'].progress_apply(preprocess_okt)
df4['review_token'] = df4['review'].progress_apply(preprocess_okt)
df5['review_token'] = df5['review'].progress_apply(preprocess_okt)
df6['review_token'] = df6['review'].progress_apply(preprocess_okt)

100%|████████████████████████████████████| 30391/30391 [04:33<00:00, 111.28it/s]


In [8]:
#빈 값 확인
empty_index = [index for index, sentence in zip(df1.index,df1['review_token']) if len(sentence) < 1]
empty_index2 = [index for index, sentence in zip(df2.index,df2['review_token']) if len(sentence) < 1]
empty_index3 = [index for index, sentence in zip(df3.index,df3['review_token']) if len(sentence) < 1]
empty_index4 = [index for index, sentence in zip(df4.index,df4['review_token']) if len(sentence) < 1]
empty_index5 = [index for index, sentence in zip(df5.index,df5['review_token']) if len(sentence) < 1]
empty_index6 = [index for index, sentence in zip(df6.index,df6['review_token']) if len(sentence) < 1]
print(empty_index, empty_index2, empty_index3, empty_index4, empty_index5, empty_index6) 

[] [] [] [] [] []


# 토큰화된 단어를 리스트로 만들기

In [10]:
total_token1 = df1['review_token'].tolist()
total_token2 = df2['review_token'].tolist()
total_token3 = df3['review_token'].tolist()
total_token4 = df4['review_token'].tolist()
total_token5 = df5['review_token'].tolist()
total_token6 = df6['review_token'].tolist()

In [ ]:
total_token1

In [18]:
# 각 리스트를 시리즈로 변환
series1 = pd.Series(total_token1, name='token1')
series2 = pd.Series(total_token2, name='token2')
series3 = pd.Series(total_token3, name='token3')
series4 = pd.Series(total_token4, name='token4')
series5 = pd.Series(total_token5, name='token5')
series6 = pd.Series(total_token6, name='token6')

# 시리즈들을 하나의 데이터프레임으로 병합
df = pd.concat([series1, series2, series3, series4, series5, series6], axis=1)
df

token1   
0      선천, 안좋다, 밀가루, 음식, 번, 먹다, 번은, 똥, 방귀, 장난, 나오다, 변...  \
1      피부관리, 어떻다, 해, 피부, 나이, 숨다, 없다, 요즘, 탄력, 떨어지다, 게,...   
2      양제, 추천, 해주, 요즘, 사람, 나, 보다, 지치다, 보, 힘들다, 보이다, 치...   
3      조금, 뭘, 피로하다, 지고, 잠, 쏟아지다, 간, 때문, 요, 예전, 체력, 소리...   
4      남편, 건강, 식품, 남편, 게, 챙기다, 공유, 해주다, 밀크, 슬, 혈액, 환제...   
...                                                  ...   
30386                                                NaN   
30387                                                NaN   
30388                                                NaN   
30389                                                NaN   
30390                                                NaN   

                                                  token2   
0      보약, 효과, 남편, 요즘, 회사, 일이, 바쁘다, 집, 말, 없다, 피곤하다, 직...  \
1      임산부, 불면증, 알, 없다, 곳, 아프다, 주, 임산부, 주전, 밤, 낮, 자다,...   
2      유산소운동, 런닝, 걷기, 등산, 꾸준하다, 암, 걸리다, 사람, 유산소운동, 암세...   
3      임산부, 감기, 약, 임신, 확인, 상태, 임신, 가능성, 감기, 약, 먹기, 조심...   
4      날씨, 갑자기, 추워지다, 아이, 기침, 때, 약, 먹이다, 제, 유난, 뜨다, 또...   
...                                                  ...   
30386                                                NaN   
30387                                                NaN   
30388                                                NaN   
30389                                                NaN   
30390                                                NaN   

                                                  token3   
0      돼지, 체력, 나가다, 돼지, 여자, 목표, 키, 개월, 생각, 정신차리다, 다이어...  \
1      소화, 차다, 어찌, 운동, 그닥, 위, 움직이다, 소화, 식도염, 좋다, 양약, ...   
2      커피믹스, 라떼, 러브, 핸들, 뱃살, 때문, 빵, 겨우, 끊다, 늘다, 달달, 음...   
3      다이어트, 용, 점심, 샐러드, 닭, 가슴, 살, 개다, 다이어트, 용, 점심, 샐...   
4      출산, 후, 살이, 빠지다, 출산, 한지, 달, 식단, 조절, 일주일, 번, 달동,...   
...                                                  ...   
30386                                                NaN   
30387                                                NaN   
30388                                                NaN   
30389                                                NaN   
30390                                                NaN   

                                                  token4   
0      집밥, 타다, 반찬, 사진, 마구, 마구, 투척, 요것, 빙산, 일각, 건강하다, ...  \
1      자취, 역류성, 식도염, 달, 살다, 먹다, 바로, 눕다, 외, 튀김, 밀가루, 인...   
2      감, 바스, 우대신, 넣다, 거, 감, 바스, 좋아하다, 새우, 알다, 새우, 대신...   
3      다이어트, 키토, 김밥, 싸다, 맛, 없다, 김밥, 먹다, 김밥, 그립다, 기분, ...   
4      코스트코, 브런치, 해먹, 추천, 상품, 알다, 코코, 아침, 대용, 먹다, 브런치...   
...                                                  ...   
30386                                                NaN   
30387                                                NaN   
30388                                                NaN   
30389                                                NaN   
30390                                                NaN   

                                                  token5   
0      오늘, 운동, 일기, 멸치, 살찌다, 멸치, 벤치, 프레, 스, 빈바, 인클라인, ...  \
1      마르다, 비만, 헬린, 근육, 찌다, 중이, 교대, 종이, 인형, 불리다, 마르다,...   
2      홈트, 대충, 년, 거, 반복, 년, 거, 헬스장, 경험, 무, 매년, 개월, 개월...   
3      유, 산소, 짧다, 끊다, 안좋다, 나, 식, 거들다, 러닝, 분, 천국, 계단, ...   
4      오운완, 헬스장, 대다, 친구, 쌩쌩하다, 나, 홍삼, 닭, 가슴, 살, 먹다, 피...   
...                                                  ...   
30386                                                NaN   
30387                                                NaN   
30388                                                NaN   
30389                                                NaN   
30390                                                NaN   

                                                  token6  
0      오늘, 도시락, 컬리, 플라워, 라이스, 볶음밥, 밥, 인척, 야채, 젛다좋다, 거...  
1      인바디, 재볼, 곳, 헬스장, 가면, 재주, 보건소, 보건소, 퇴근, 시간, 보건소...  
2      회식, 점심, 좋다, 퇴근, 시간, 내다, 두다, 안되다, 아아, 콜, 제발, 술,...  
3      홍삼, 제품, 먹다, 때, 커피, 먹다, 안좋다, 누가, 그렇다, 사포닌, 성분, ...  
4      저녁, 외식, 메뉴, 정, 비빔밥, 포케, 서브웨이, 카레, 파스타, 계속, 돌리다...  
...                                                  ...  
30386           루테, 추천, 아버지, 백내장

In [19]:
df.to_csv('total_token_임시저장.csv', encoding = 'utf-8-sig')

## 동시출현매트릭스 만들기 > 여기부턴 왔다갔다 하기...파일 섞이면 대참사

In [2]:
df = pd.read_csv('total_token_임시저장.csv', encoding = 'utf-8-sig', index_col = 0)

import ast
from tqdm import tqdm

tqdm.pandas()

def literal_eval(val):
    try:
        return ast.literal_eval(val)
    except (ValueError, SyntaxError):
        return val  # 변환에 실패한 경우 원래 값을 반환

df['token1'] = df['token1'].progress_apply(literal_eval)
total_token1 = df['token1'].dropna().tolist()

100%|███████████████████████████████████| 30391/30391 [00:04<00:00, 6200.66it/s]


In [3]:
# 동시출현빈도 매트릭스
cv=CountVectorizer()

X = cv.fit_transform(total_token1)
Xc = (X.T * X)
Xc.setdiag(0) #대각선 원소를 0으로
Xc=Xc.todense() # 밀집행렬로 변형 (matrix형으로)

names = cv.get_feature_names_out()

#Xc.toarray() .todense와 같지만 array형태로 만들어줘서 dataframe에 넣음
matrix = pd.DataFrame(data =Xc, columns = names, index = names)
matrix.index

/Users/seungminkoo/miniforge3/lib/python3.10/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


Index(['가가', '가감', '가게', '가겐', '가격', '가격표', '가경동', '가계부', '가곡', '가공',
       ...
       '힙업된', '힙업모드', '힙업효', '힙퓨레', '힙프레', '힙한', '힙합', '힙해', '힝구', '힝힝'],
      dtype='object', length=37954)

## 만약 평균 기준으로 cutoff 한다면!
- 노드 빈도가 평균 이상일 경우만 살려주고 싶다면 사용하세요
- 데이터를 가볍게 만들길 원한다면,,

[reference]

하지만 빈도수 매트릭스의 경우 모든 키워드에 연결관계가 나타나 복잡할 가능성이 존재하기 때문에 매트릭스의 평균값을 기준(cut-off value)으로 평균보다 클 경우 1을, 작을 경우 0을 반환하여(slicing)새로운 바이너리 매트릭스(binary matrix)를 생성하였다(정풀잎 외, 2019; John Scott, 2012).

In [4]:
mean_val = np.mean(Xc[Xc!=0]) # Xc의 평균값 계산
Xc[Xc < int(mean_val)] = 0 # 평균 이하인 값을 0으로 바꾸기

In [5]:
# Xc를 numpy array로 변환
Xc = np.array(Xc)

# 각 행과 열의 합 구하기
row_sum = np.sum(Xc, axis=1)
col_sum = np.sum(Xc, axis=0)

# 합이 0인 인덱스 찾기
zero_row_idx = np.where(row_sum == 0)[0]
zero_col_idx = np.where(col_sum == 0)[0]

# 해당 인덱스 삭제
Xc = np.delete(Xc, zero_row_idx, axis=0)
Xc = np.delete(Xc, zero_col_idx, axis=1)

# 결과 출력
print(Xc)
Xc.shape

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


(24658, 24658)

In [6]:
names = cv.get_feature_names_out()
Name = [val for i, val in enumerate(names) if i not in zero_row_idx]
matrix = pd.DataFrame(data =Xc, columns = Name, index = Name)
matrix.index

Index(['가가', '가감', '가게', '가격', '가격표', '가계부', '가곡', '가공', '가공품', '가구',
       ...
       '힙보', '힙분유', '힙쓰', '힙쓰루', '힙업', '힙업된', '힙퓨레', '힙프레', '힙해', '힝구'],
      dtype='object', length=24658)

In [7]:
matrix.to_csv('co-occurrence matrix_cluster0.csv', encoding = 'utf-8-sig', sep = ',')

### 용량 너무 큰 애들 줄이기....

In [5]:
matrix = pd.read_csv('co_occurrence matrix_cluster4.csv', encoding = 'utf-8-sig', index_col = 0)

In [6]:
from ast import literal_eval

# 데이터프레임을 생성하는 예제 (이미 불러온 데이터프레임을 사용하세요)
# df = pd.read_csv('your_file.csv')

# 모든 셀에 대해 literal_eval을 적용하는 함수
def convert_to_numeric(cell):
    try:
        return literal_eval(cell)
    except (ValueError, SyntaxError):
        return cell

# 데이터프레임에 applymap 함수를 사용하여 각 셀을 변환
matrix = matrix.applymap(convert_to_numeric)

# 변환된 데이터프레임 인덱스만 출력
matrix.index

가가  가각  가감  가게  가겐  가겟슴다  가겠슴다  가격  가격르  가격표  ...  힙합  힙힌  힙힌지  힙힌지더  힙힠   
가가   0   0   0   0   0     0     0  16    0    0  ...   0   0    0     0   0  \
가각   0   0   0   0   0     0     0   0    0    0  ...   0   0    0     0   0   
가감   0   0   0   0   0     0     0   0    0    0  ...   0   0    0     0   0   
가게   0   0   0   0   0     0     0  39    0    0  ...   0   0    0     0   0   
가겐   0   0   0   0   0     0     0   0    0    0  ...   0   0    0     0   0   
..  ..  ..  ..  ..  ..   ...   ...  ..  ...  ...  ...  ..  ..  ...   ...  ..   
힝구   0   0   0   0   0     0     0   0    0    0  ...   0   0    0     0   0   
힝규   0   0   0   0   0     0     0   0    0    0  ...   0   0    0     0   0   
힝드   0   0   0   0   0     0     0   0    0    0  ...   0   0    0     0   0   
힝힝   0   0   0   0   0     0     0   0    0    0  ...   0   0    0     0   0   
힢라   0   0   0   0   0     0     0   0    0    0  ...   0   0    0     0   0   

    힝구  힝규  힝드  힝힝  힢라  
가가   0   0   0   0   0  
가각   0   0   0   0   0  
가감   0   0   0   0   0  
가게   0   0   0   0   0  
가겐   0   0   0   0   0  
..  ..  ..  ..  ..  ..  
힝구   0   0   0   0   0  
힝규   0   0   0   0   0  
힝드   0   0   0   0   0  
힝힝   0   0   0   0   0  
힢라   0   0   0   0   0  

[43658 rows x 43658 columns]

In [11]:
# 각 키워드 동시출현 빈도의 합 계산
keyword_sums = matrix.sum(axis=1)

# 상위 n개의 키워드 > 승민 임의로 만개로 설정
n = 10000
top_keywords = keyword_sums.nlargest(n).index

# 상위 키워드에 해당하는 행과 열만 선택
reduced_co_occurrence_matrix = matrix.loc[top_keywords, top_keywords]

reduced_co_occurrence_matrix.index

Index(['운동', '보다', '먹다', '좋다', '없다', '그렇다', '자다', '해보다', '시간', '아이',
       ...
       '이소라', '난소', '마녀', '솥밥', '시드라', '쌀국수', '자영', '찰싹', '대접받다', '랜선'],
      dtype='object', length=10000)

In [12]:
reduced_co_occurrence_matrix

운동      보다      먹다      좋다     없다    그렇다     자다    해보다     시간   
운동         0  108914  116336  102885  84918  67481  59215  61154  52724  \
보다    108914       0   81877   73190  61580  54325  52324  39191  36668   
먹다    116336   81877       0   62144  63996  58684  59238  31746  39599   
좋다    102885   73190   62144       0  46995  40152  40727  33525  27714   
없다     84918   61580   63996   46995      0  39697  35281  26404  27069   
...      ...     ...     ...     ...    ...    ...    ...    ...    ...   
쌀국수       18      30     133      28     19     24      0      0      0   
자영         0      24      28      23     41     23     27      0      0   
찰싹        39      38      17      36     17     40     14     13      0   
대접받다       0       0     125      16      0     66     16      0      0   
랜선        14      42      43      33     26     20     25     12      0   

         아이  ...  이소라  난소  마녀  솥밥  시드라  쌀국수  자영  찰싹  대접받다  랜선  
운동    12119  ...   41  17  18   0   53   18   0  39     0  14  
보다    41519  ...   27  27   0  18   34   30  24  38     0  42  
먹다    25720  ...   68  26  28  41   13  133  28  17   125  43  
좋다    32813  ...    0  24  16   0   30   28  23  36    16  33  
없다    24506  ...   17  26   0   0   37   19  41  17     0  26  
...     ...  ...  ...  ..  ..  ..  ...  ...  ..  ..   ...  ..  
쌀국수       0  ...    0   0   0   0    0    0   0   0     0   0  
자영        0  ...    0   0   0   0    0    0   0   0     0   0  
찰싹        0  ...    0   0   0   0    0    0   0   0     0   0  
대접받다      0  ...    0   0   0   0    0    0   0   0     0   0  
랜선        0  ...    0   0   0   0    0    0   0   0     0   0  

[10000 rows x 10000 columns]

In [13]:
reduced_co_occurrence_matrix.to_csv('reduced_co-occurrence matrix_cluster4.csv', encoding = 'utf-8-sig', sep = ',')